platform :ios, '8.3'
use_frameworks!

target 'Debts' do
	pod 'Alamofire', '~> 3.4'
	pod 'SwiftyJSON', '~> 2.3'    
	pod 'RSBarcodes_Swift', '~> 0.1'
	pod 'PayPal-iOS-SDK', '~> 2.14'
	pod 'SwiftAddressBook', '~> 0.6'
end