platform :ios, '8.0'
use_frameworks!

target 'Debts' do
    pod 'SwiftAddressBook', '~> 0.4.3'
    pod 'Alamofire', '~> 1.2'
    pod 'SwiftyJSON', '~> 2.2.0'
    pod 'RSBarcodes_Swift', '~> 0.0.8'
end